### ISSUE TITLE
Add TravisCI Testing

### ISSUE THREAD

**Issue by mprahl** [fedora-infra/pdc-updater#26]
As a developer or maintainer of pdc-updater, I'd like to have TravisCI testing enabled so that changes are tested before they are merged.

For this to work, I believe we'll have to have `swig` installed by TravisCI such as at:
https://github.com/release-engineering/resultsdb-updater/blob/master/.travis.yml#L5

A potential blocker could be `koji` being a dependency.

**Comment by mprahl** [comment]
An option here is to use a Fedora container for testing.

**Comment by ralphbean** [comment]
See the [mailing list thread](https://lists.fedorahosted.org/archives/list/koji-devel@lists.fedorahosted.org/thread/XLIR4DSXXRU3OYWXEZWJQJAEEIOUQEXY/) about getting koji on pypi.

**Comment by junaruga** [comment]
The actual discussion is also in https://pagure.io/koji/issue/458 .

**Comment by mprahl** [comment]
PR #78 addresses this
