### ISSUE TITLE
Make topic suffix configurable

### ISSUE THREAD

**Issue by mprahl** [fedora-infra/pdc-updater#42]
If pdc-updater is configured to connect to a message bus using STOMP, it will use a hardcoded value of "brew.build.tag" as a topic suffix (1). Since the "brew" portion of the topic suffix is configurable on the Koji messaging plugin, this should be configurable on pdc-updater to allow other deployments that use STOMP that aren't Brew.

1 - https://github.com/fedora-infra/pdc-updater/blob/66e0e831688910073526fd68806c29b1277416cb/pdcupdater/handlers/depchain/base.py#L29

**Comment by ralphbean** [comment]
This issue is over a year old.  Going to close it as a part of backlog grooming.
