### ISSUE TITLE
Allow the use of keytabs for authentication with PDC instead of tokens

### ISSUE THREAD

**Issue by mprahl** [fedora-infra/pdc-updater#46]
Currently, pdc-updater uses tokens that the user has to manually generate for authentication with PDC. It'd be nice if pdc-updater could use a kerberos keytab to generate a kerberos ticket and get it's own token. That way if for whatever reason the token gets removed from the PDC instance, the service could still authenticate without changing pdc-updater's configuration.

There are some examples of fedmsg based services that do this already. We should utilize their code as a starting off point.

**Comment by puiterwijk** [comment]
For the Fedora instance, I do not want any new services to get keytabs.
We should instead be moving everything to OAuth2 tokens.

For any other instances, I do not have any say in those, and I'm fine with having the code implemented for them.

**Comment by ralphbean** [comment]
IIRC, @mikebonnet has advised that we use the `python-gssapi` library for implementing kerberos support in applications.

**Comment by ralphbean** [comment]
Fixed by #69.
