### ISSUE TITLE
Fill data for PDC /build-images/ endpoint

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/pdc-updater#55]
I'm working on a freshmaker issue that rebuilds docker image when a rpm is available in official repositories. To fix that issue, I need to query which docker image contains a specific RPM. PDC has an endpoint ``/build-images/``, but there is no data currently in https://pdc.fedoraproject.org/rest_api/v1/build-images/.

**Comment by ralphbean** [comment]
Sorry, I never documented this *and* it's been disabled in production until we needed it (now).

Try using the release-component-relationships endpoint, like here:

- https://pdc.stg.fedoraproject.org/rest_api/v1/release-component-relationships/?type=ContainerIncludesRPM

**Comment by ralphbean** [comment]
The code that populates that endpoint was written specifically to provide data for this use case *but* it was written almost a year ago.

If you find that the data doesn't meet your needs, let's circle back on it and change it.

**Comment by tkdchen** [comment]
I checked stg firstly, I think result from ``/release-component-relationships/`` is usable so far. However, a few questions about a release component, e.g. cockpit[1]

Why ``dist_git_branch`` is ``null``? Its value would be useful to determine from which branch to rebuild the docker image.

What is ``brew_package`` used for? Now, it's null too. Does it have same value with ``name`` generally? Will it be enabled and used?

``dist_git_web_url`` has a fake repository link. Is this because it is on a stg? Making it real value would be helpful for applications like freshmaker, which require stg PDC for whatever the purpose.

Another question is about ``cockpit``[2] in prod. Its ``type`` is ``rpm`` instead of ``container``. Somethng is wrong?

[1] https://pdc.stg.fedoraproject.org/rest_api/v1/release-components/5430/
[2] https://pdc.fedoraproject.org/rest_api/v1/release-components/263070/

**Comment by ralphbean** [comment]
This card needs to be broken into multiple cards to handle the two pieces about branch and web_url.  They are both currently empty, but for no good reason.  pdc-updater should put in good values.

The missing cockpit container in the prod pdc db is also a bug that deserves its own ticket to track down.
